updated dependencies
jonschlinkert/cache-base pull request #25
Opened 2021-09-30 15:47 UTC by jimmywarting

fyi, tried updating set-value to v4 also but it had a breaking change...
otherwise the test runs just fine

2021-10-08 13:59 UTC, brunoscit requested changes

2021-10-08 13:59 UTC, brunoscit commented on package.json
> +    "set-value": "^3.0.2",
can you please update to 4.0.1, there is a high security vulnerability with that version.

https://github.com/advisories/GHSA-4jqc-8m5r-9rpr

Thank you!

P.S: I saw your comment that you can't use version 4 but we can't use this module without this update =[

2021-10-08 14:02 UTC, brunoscit commented
> fyi, tried updating set-value to v4 also but it had a breaking change... otherwise the test runs just fine

We can't use it in a version less than 4.0.1, there is a high security issue =[ 
https://github.com/advisories/GHSA-4jqc-8m5r-9rpr

2021-10-08 20:23 UTC, jimmywarting commented on package.json
> +    "set-value": "^3.0.2",
bumped to 4.1.0

2021-11-06 22:28 UTC, jonschlinkert commented
resolved by https://github.com/jonschlinkert/cache-base/pull/23. I do appreciate the PR, thank you.

2021-11-06 22:28 UTC, closed without merging